namespace eOne.Common.Connectors.HubSpot.Models
{
    public class HubspotContactProperties
    {

        public HubspotProperty firstname { get; set; }
        public HubspotProperty lastname { get; set; }
        public HubspotProperty company { get; set; }
        public HubspotProperty email { get; set; }
        public HubspotProperty lastmodifieddate { get; set; }
        public HubspotProperty days_to_close { get; set; }
        public HubspotProperty first_conversion_date { get; set; }
        public HubspotProperty first_conversion_event_name { get; set; }
        public HubspotProperty first_deal_created_date { get; set; }
        public HubspotProperty hs_emailconfirmationstatus { get; set; }
        public HubspotProperty hs_facebookid { get; set; }
        public HubspotProperty hs_googleplusid { get; set; }
        public HubspotProperty hs_ip_timezone { get; set; }
        public HubspotProperty hs_lead_status { get; set; }
        public HubspotProperty hs_linkedinid { get; set; }
        public HubspotProperty hs_twitterid { get; set; }
        public HubspotProperty hubspot_owner_assigneddate { get; set; }
        public HubspotProperty ip_city { get; set; }
        public HubspotProperty ip_country { get; set; }
        public HubspotProperty ip_country_code { get; set; }
        public HubspotProperty ip_latlon { get; set; }
        public HubspotProperty ip_state { get; set; }
        public HubspotProperty ip_state_code { get; set; }
        public HubspotProperty ip_zipcode { get; set; }
        public HubspotProperty num_associated_deals { get; set; }
        public HubspotProperty num_conversion_events { get; set; }
        public HubspotProperty num_unique_conversion_events { get; set; }
        public HubspotProperty recent_conversion_date { get; set; }
        public HubspotProperty recent_conversion_event_name { get; set; }
        public HubspotProperty recent_deal_amount { get; set; }
        public HubspotProperty recent_deal_close_date { get; set; }
        public HubspotProperty total_revenue { get; set; }
        public HubspotProperty blog_default_hubspot_blog_subscription { get; set; }
        public HubspotProperty hs_analytics_first_url { get; set; }
        public HubspotProperty hs_email_delivered { get; set; }
        public HubspotProperty twitterhandle { get; set; }
        public HubspotProperty currentlyinworkflow { get; set; }
        public HubspotProperty followercount { get; set; }
        public HubspotProperty hs_analytics_last_url { get; set; }
        public HubspotProperty hs_email_open { get; set; }
        public HubspotProperty hs_analytics_num_page_views { get; set; }
        public HubspotProperty hs_email_click { get; set; }
        public HubspotProperty salutation { get; set; }
        public HubspotProperty twitterprofilephoto { get; set; }
        public HubspotProperty hs_analytics_num_visits { get; set; }
        public HubspotProperty hs_email_bounce { get; set; }
        public HubspotProperty hs_persona { get; set; }
        public HubspotProperty hs_social_last_engagement { get; set; }
        public HubspotProperty hs_analytics_num_event_completions { get; set; }
        public HubspotProperty hs_email_optout { get; set; }
        public HubspotProperty hs_social_twitter_clicks { get; set; }
        public HubspotProperty mobilephone { get; set; }
        public HubspotProperty phone { get; set; }
        public HubspotProperty fax { get; set; }
        public HubspotProperty hs_analytics_first_timestamp { get; set; }
        public HubspotProperty hs_email_last_email_name { get; set; }
        public HubspotProperty hs_email_last_send_date { get; set; }
        public HubspotProperty hs_social_facebook_clicks { get; set; }
        public HubspotProperty address { get; set; }
        public HubspotProperty hs_analytics_first_visit_timestamp { get; set; }
        public HubspotProperty hs_email_last_open_date { get; set; }
        public HubspotProperty hs_social_linkedin_clicks { get; set; }
        public HubspotProperty hubspot_owner_id { get; set; }
        public HubspotProperty notes_last_contacted { get; set; }
        public HubspotProperty notes_last_updated { get; set; }
        public HubspotProperty notes_next_activity_date { get; set; }
        public HubspotProperty num_contacted_notes { get; set; }
        public HubspotProperty num_notes { get; set; }
        public HubspotProperty surveymonkeyeventlastupdated { get; set; }
        public HubspotProperty webinareventlastupdated { get; set; }
        public HubspotProperty city { get; set; }
        public HubspotProperty hs_analytics_last_timestamp { get; set; }
        public HubspotProperty hs_email_last_click_date { get; set; }
        public HubspotProperty hs_social_google_plus_clicks { get; set; }
        public HubspotProperty linkedinbio { get; set; }
        public HubspotProperty twitterbio { get; set; }
        public HubspotProperty hs_analytics_last_visit_timestamp { get; set; }
        public HubspotProperty hs_email_first_send_date { get; set; }
        public HubspotProperty hs_social_num_broadcast_clicks { get; set; }
        public HubspotProperty state { get; set; }
        public HubspotProperty hs_analytics_source { get; set; }
        public HubspotProperty hs_email_first_open_date { get; set; }
        public HubspotProperty zip { get; set; }
        public HubspotProperty country { get; set; }
        public HubspotProperty hs_analytics_source_data_1 { get; set; }
        public HubspotProperty hs_email_first_click_date { get; set; }
        public HubspotProperty linkedinconnections { get; set; }
        public HubspotProperty hs_analytics_source_data_2 { get; set; }
        public HubspotProperty hs_email_is_ineligible { get; set; }
        public HubspotProperty jobtitle { get; set; }
        public HubspotProperty kloutscoregeneral { get; set; }
        public HubspotProperty hs_analytics_first_referrer { get; set; }
        public HubspotProperty hs_email_lastupdated { get; set; }
        public HubspotProperty message { get; set; }
        public HubspotProperty photo { get; set; }
        public HubspotProperty closedate { get; set; }
        public HubspotProperty hs_analytics_last_referrer { get; set; }
        public HubspotProperty hs_analytics_average_page_views { get; set; }
        public HubspotProperty lifecyclestage { get; set; }
        public HubspotProperty hs_analytics_revenue { get; set; }
        public HubspotProperty hs_lifecyclestage_lead_date { get; set; }
        public HubspotProperty hs_lifecyclestage_marketingqualifiedlead_date { get; set; }
        public HubspotProperty hs_lifecyclestage_opportunity_date { get; set; }
        public HubspotProperty ipaddress { get; set; }
        public HubspotProperty createdate { get; set; }
        public HubspotProperty hs_lifecyclestage_salesqualifiedlead_date { get; set; }
        public HubspotProperty hs_lifecyclestage_evangelist_date { get; set; }
        public HubspotProperty hubspotscore { get; set; }
        public HubspotProperty hs_lifecyclestage_customer_date { get; set; }
        public HubspotProperty hs_lifecyclestage_subscriber_date { get; set; }
        public HubspotProperty website { get; set; }
        public HubspotProperty hs_lifecyclestage_other_date { get; set; }
        public HubspotProperty numemployees { get; set; }
        public HubspotProperty annualrevenue { get; set; }
        public HubspotProperty industry { get; set; }
        public HubspotProperty associatedcompanyid { get; set; }
        public HubspotProperty associatedcompanylastupdated { get; set; }
        public HubspotProperty hs_predictivecontactscore { get; set; }

    }
}