//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApna
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public double Quntity { get; set; }
        public decimal Cost { get; set; }
    }
}
